name: Check CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  

jobs:
  lint:
    runs-on: ubuntu-latest 

    steps:
      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.1

      - name: Run make lint
        run: make lint

  test:
    runs-on: ubuntu-latest 

    depends-on: lint

    steps:
      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22

      - name: Run make test
        run: make test
